<?php

namespace Rokka\DBundle\Repository;

use \Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Response;


/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findByNameLike($name)
    {
        $repository = $this->getEntityManager()->getRepository('RokkaDBundle:Category');
        $query = $repository->createQueryBuilder('c')
            ->where('c.name = :name')
            ->setParameter('name', $name)
            ->orderBy('c.name', 'ASC')
            ->getQuery();
        $goods = $query->getResult();

        return new Response($goods);
    }
}
