<?php

namespace Rokka\DBundle\Repository;

/**
 * Пщ�GoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Пщ�GoodsRepository extends \Doctrine\ORM\EntityRepository
{
}
